### ISSUE TITLE
llc crashes in NaCL ExpandLargeIntegers.cpp

### ISSUE THREAD

**Issue by hpohl** [emscripten-core/emscripten-fastcomp#250]
While trying to create a side module from an empty rust library, I encountered this crash:

```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.38.21 (commit df648b43825d3ab1179886d3c78020ed890333d3)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
$ rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)

$ cat lib.rs

$ rustc lib.rs --target wasm32-unknown-emscripten --crate-type staticlib

$ emcc liblib.a -o liblib.wasm -s SIDE_MODULE=1
#0 0x000000000130b50a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x130b50a)
#1 0x00000000013095ee llvm::sys::RunSignalHandlers() (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x13095ee)
#2 0x000000000130973c SignalHandler(int) (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x130973c)
#3 0x00007f6e9f9503c0 __restore_rt (/usr/lib/libpthread.so.0+0x123c0)
#4 0x0000000000e36423 llvm::Value::getContext() const (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0xe36423)
#5 0x00000000014d68ee convertInstruction(llvm::Instruction*, (anonymous namespace)::ConversionState&, llvm::DataLayout const&) [clone .constprop.227] (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x14d68ee)
#6 0x00000000014db517 (anonymous namespace)::ExpandLargeIntegers::runOnFunction(llvm::Function&) (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x14db517)
#7 0x0000000000df66ba llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0xdf66ba)
#8 0x0000000000df6763 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0xdf6763)
#9 0x0000000000df6274 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0xdf6274)
#10 0x000000000060a0f7 compileModule(char**, llvm::LLVMContext&) [clone .constprop.394] (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x60a0f7)
#11 0x00000000005c2d3d main (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x5c2d3d)
#12 0x00007f6e9f46b223 __libc_start_main (/usr/lib/libc.so.6+0x24223)
#13 0x00000000005fee79 _start (/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc+0x5fee79)
Stack dump:
0.	Program arguments: /home/henning/clones/emsdk/clang/e1.38.21_64bit/llc /tmp/tmpYcbq4X/liblib.bc -march=js -filetype=asm -o /tmp/tmp3vF_K8.4.js -emscripten-stack-size=5242880 -O0 -emscripten-precise-f32 -emscripten-assertions=1 -emscripten-no-aliasing-function-pointers -emscripten-emulated-function-pointers -emscripten-relocatable -emscripten-global-base=0 -emscripten-side-module -emscripten-no-exit-runtime -emscripten-wasm 
1.	Running pass 'Function Pass Manager' on module '/tmp/tmpYcbq4X/liblib.bc'.
2.	Running pass 'Expand integer types that are illegal in PNaCl' on function '@"_ZN3std3net2ip84_$LT$impl$u20$core..convert..From$LT$std..net..ip..Ipv6Addr$GT$$u20$for$u20$u128$GT$4from17hf1f961eba817b191E"'
Traceback (most recent call last):
  File "/home/henning/clones/emsdk/emscripten/1.38.21/emcc.py", line 3090, in <module>
    sys.exit(run())
  File "/home/henning/clones/emsdk/emscripten/1.38.21/emcc.py", line 1805, in run
    final = shared.Building.emscripten(final, target + '.mem', js_libraries)
  File "/home/henning/clones/emsdk/emscripten/1.38.21/tools/shared.py", line 2221, in emscripten
    emscripten.main(infile, outfile, memfile, js_libraries)
  File "/home/henning/clones/emsdk/emscripten/1.38.21/emscripten.py", line 2260, in main
    return temp_files.run_and_clean(lambda: emscripter(
  File "/home/henning/clones/emsdk/emscripten/1.38.21/tools/tempfiles.py", line 100, in run_and_clean
    return func()
  File "/home/henning/clones/emsdk/emscripten/1.38.21/emscripten.py", line 2261, in <lambda>
    infile, outfile_obj, memfile, libraries, shared.COMPILER_ENGINE, temp_files, get_configuration().DEBUG)
  File "/home/henning/clones/emsdk/emscripten/1.38.21/emscripten.py", line 92, in emscript
    backend_output = compile_js(infile, temp_files, DEBUG)
  File "/home/henning/clones/emsdk/emscripten/1.38.21/emscripten.py", line 121, in compile_js
    jsrun.timeout_run(subprocess.Popen(backend_args, stdout=subprocess.PIPE, universal_newlines=True), note_args=backend_args)
  File "/home/henning/clones/emsdk/emscripten/1.38.21/tools/jsrun.py", line 24, in timeout_run
    raise Exception('Subprocess "' + ' '.join(note_args) + '" failed with exit code ' + str(proc.returncode) + '!')
Exception: Subprocess "/home/henning/clones/emsdk/clang/e1.38.21_64bit/llc /tmp/tmpYcbq4X/liblib.bc -march=js -filetype=asm -o /tmp/tmp3vF_K8.4.js -emscripten-stack-size=5242880 -O0 -emscripten-precise-f32 -emscripten-assertions=1 -emscripten-no-aliasing-function-pointers -emscripten-emulated-function-pointers -emscripten-relocatable -emscripten-global-base=0 -emscripten-side-module -emscripten-no-exit-runtime -emscripten-wasm" failed with exit code -11!
```
Not using `-s SIDE_MODULE=1` works just fine.

**Comment by kripken** [comment]
Hmm, perhaps rust adds some support code even in an empty library, and that hits the bug? Can look in liblib.a to see what's there.

In general, though, it's probably more interesting to use emcc with the LLVM wasm backend at this point, instead of fixing fastcomp bugs. Options like SIDE_MODULE should work with both backends now I believe, or soon will.

**Comment by hpohl** [comment]
Sorry for the late response.

I agree. Looks like at this point it's not supported (latest emscripten, binaryen and llvm):
`emcc: MAIN_MODULE and SIDE_MODULE are not yet supported by the LLVM wasm backend`
